### PCA using Eigendecomposition

This is the main technique with which PCA was first done. Then later on SVD algorithms came into place which uses an equivalent way of doing PCA but is much faster than that.

In [17]:
import pandas as pd 
import numpy as np

In [33]:
#Let's take this dataset
a = [[0,0],[1,2],[2,3],[3,6],[4,8],[5,9]]
b = ['X','Y']
dat = pd.DataFrame(a,columns = b)
dat

X  Y
0  0  0
1  1  2
2  2  3
3  3  6
4  4  8
5  5  9

### Step 1 : Create the Covariance Matrix

In [34]:
#Let's create the covariance matrix here.
# An intuitive reason as to why we're doing this is to capture the variance of the entire dataset
C = np.cov(dat.T)
C

array([[ 3.5       ,  6.6       ],
       [ 6.6       , 12.66666667]])

### Step 2 : Eigendecomposition of the Covariance Matrix

In [35]:
eigenvalues, eigenvectors = np.linalg.eig(C)

In [36]:
eigenvectors

array([[-0.88611393, -0.46346747],
       [ 0.46346747, -0.88611393]])

In [37]:
eigenvalues

array([ 0.04797743, 16.11868923])

In [38]:
#Let's sort them now
idx = eigenvalues.argsort()[::-1]   
eigenvalues= eigenvalues[idx]
eigenvectors = eigenvectors[:,idx]

In [39]:
#Let's check them again
eigenvalues

array([16.11868923,  0.04797743])

In [40]:
eigenvectors

array([[-0.46346747, -0.88611393],
       [-0.88611393,  0.46346747]])

In [45]:
Cnew = np.linalg.inv(eigenvectors) @ dat.T
cols  = ['X','Y']
Cnewt = pd.DataFrame(Cnew.T)
Cnewt.columns= cols
Cnewt

X         Y
0   0.000000  0.000000
1  -2.235695  0.040821
2  -3.585277 -0.381825
3  -6.707086  0.122463
4  -8.942781  0.163284
5 -10.292363 -0.259362

In [46]:
100*np.var(Cnewt)/sum(np.var(Cnewt))

X    99.703232
Y     0.296768
dtype: float64

### Let's check it using pca function that we used earlier

In [47]:
from sklearn.decomposition import PCA
pca = PCA(svd_solver='randomized', random_state=42)

In [48]:
pca.fit(dat)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=42,
  svd_solver='randomized', tol=0.0, whiten=False)

In [49]:
#Let's check the components
pca.components_

array([[-0.46346747, -0.88611393],
       [ 0.88611393, -0.46346747]])

As you can see the directions obtained here is nearly the same as obtained through the eigendecomposition.

Note that the columns in the eigenvector matrix are to be compared with the rows of pca.components_ matrix. Also the directions are reversed for the second axis. This wouldn't make a difference as even though they're antiparallel, they would represent the same 2-D space. For example, X/Y and X/-Y both cover the entire 2-D plane

In [50]:
#Let's check the variance explained
pca.explained_variance_ratio_

array([0.99703232, 0.00296768])

This is also almost the same

#### Thus we've verified the algorithm of PCA.

## But why?

Because Spectral Theorem exists! Because of this theorem eigendecomposition of the covariance matrix will always:
1. Yield the eigenvectors which are perpendicular to each other 
2. Have maximum variances allocated to them in an ordered way depending on the magnitude of the eigenvalues.