## SVD Example

In [1]:
import pandas as pd
import numpy as np

In [2]:
ratings = pd.read_csv("Book-Ratings.csv")

In [3]:
ratings

ITHALS  FPS  HG  MM  TW
0       1    1   0   0   1
1       4    5   4   0   0
2       5    4   4   0   0
3       5    3   3   0   1
4       1    1   0   5   4
5       0    1   0   4   5
6       0    0   2   2   3

In [25]:
#Let's go ahead and apply SVD and try to interpret the hidden themes
U,s,VT = np.linalg.svd(ratings, full_matrices = False)

In [38]:
U.round(2)

array([[-0.11, -0.04,  0.23,  0.14,  0.6 ],
       [-0.56,  0.22, -0.09, -0.69,  0.14],
       [-0.56,  0.23, -0.02,  0.07, -0.26],
       [-0.5 ,  0.12,  0.14,  0.68,  0.09],
       [-0.23, -0.61,  0.42, -0.07, -0.54],
       [-0.18, -0.64,  0.02, -0.1 ,  0.5 ],
       [-0.16, -0.33, -0.86,  0.17, -0.09]])

In [39]:
s

array([12.84011377,  9.42742035,  2.13082549,  1.71122853,  1.33660146])

In [40]:
VT

array([[-0.6139509 , -0.55003891, -0.49036141, -0.17005941, -0.22615695],
       [ 0.20937193,  0.11442495,  0.15842158, -0.66318615, -0.69148902],
       [ 0.42489821,  0.27139293, -0.81088614,  0.20823085, -0.21192209],
       [ 0.61164139, -0.68201127, -0.0529186 , -0.25503708,  0.30481329],
       [-0.15679285,  0.3815372 , -0.27223442, -0.65027681,  0.57695222]])

In [41]:
S = np.diag(s)
S

array([[12.84011377,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  9.42742035,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.13082549,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.71122853,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.33660146]])